name: Start API Test

on:
  schedule:
    - cron: "14 5 * * 1-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install Apidog CLI
        run: npm install -g apidog-cli

      - name: Running Test Scenario
        run: apidog run --access-token ${{ secrets.APIDOG_ACCESS_TOKEN }} -t 818054 -e 2531384 -n 1 --delay-request 5000 -r html,json --out-dir reports/$(date +%Y-%m-%d_%H:%M:%S)

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Commit and Push Reports
        run: |
          git add reports/
          git commit -m "Add reports from automated run of Start Tests" || echo "No changes to commit"
          git push origin HEAD:gh-pages
